# Generated by Django 2.2.14 on 2021-08-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdidos',
            name='data_perdido',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
