# Generated by Django 2.2.14 on 2021-08-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210825_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdidos',
            name='data_perdido',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
